[package]
name = "client"
edition = "2024"

[dependencies]
futures = { version = "0.3" }
tokio = { version = "1", features = ["macros", "time", "rt-multi-thread"] }
xpc-connection = { path = "../../xpc-connection" }
