name: CI

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
        rust: [ nightly, stable ]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install the toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build, run, and test the echo agent and daemon
        run: cd examples && make test

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --ignored

  lints:
    name: Lints
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install the stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: clippy
          args: -- -D warnings
